import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    dashboard: "Dashboard",
    insights: "Insights",
    addPrice: "Add Price",
    profile: "Profile",
    smartMandiSystem: "Smart Mandi Intelligence System",
    realTimeInsights: "Real-time market insights to help you sell at the best price",
    topCommodity: "Top Commodity Today",
    highestMarketPrice: "Highest Market Price",
    marketTrend: "Market Trend",
    marketsUp: "Markets Up",
    bullish: "Bullish",
    stable: "Stable",
    strong: "Strong",
    neutral: "Neutral",
    loading: "Loading...",
    allStates: "All States",
    allCommodities: "All Commodities",
    allMarkets: "All Markets",
    state: "State",
    commodity: "Commodity",
    market: "Market",
    resetFilters: "Reset Filters",
    liveMandiPrices: "Live Mandi Prices",
    realTimeIntelligence: "Real-time market intelligence for smart decisions",
    price: "Price",
    msp: "MSP",
    status: "Status",
    suggestion: "Suggestion",
    lastUpdated: "Last Updated",
    marketBased: "Market-based",
    profit: "Profit",
    loss: "Loss",
    sellNow: "SELL NOW",
    wait: "WAIT",
    tryGovtProcurement: "TRY GOVT PROCUREMENT",
    fetchingData: "Fetching live market data...",
    noPricesAvailable: "No prices available for the selected filters.",
    best: "Best",
    today: "Today",
    marketInsights: "Market Insights",
    deepAnalysis: "Deep analysis of current market trends",
    yesterdayPrice: "Yesterday's Price",
    yesterday: "Yesterday",
    weeklyComparison: "Weekly Comparison",
    historicalTrend: "Historical Trend (3 Months)",
    avgPrice: "Avg Price",
    highest: "Highest",
    lowest: "Lowest",
  },
  te: {
    dashboard: "డాష్‌బోర్డ్",
    insights: "అంతర్దృష్టులు",
    addPrice: "ధరను జోడించండి",
    profile: "ప్రొఫైల్",
    smartMandiSystem: "స్మార్ట్ మండి ఇంటెలిజెన్స్ సిస్టమ్",
    realTimeInsights: "ఉత్తమ ధరకు విక్రయించడంలో మీకు సహాయపడే నిజ-సమయ మార్కెట్ అంతర్దృష్టులు",
    topCommodity: "నేటి అగ్ర వస్తువు",
    highestMarketPrice: "అత్యధిక మార్కెట్ ధర",
    marketTrend: "మార్కెట్ ట్రెండ్",
    marketsUp: "మార్కెట్లు పెరిగాయి",
    bullish: "బుల్లిష్",
    stable: "స్థిరమైనది",
    strong: "బలమైనది",
    neutral: "తటస్థమైనది",
    loading: "లోడ్ అవుతోంది...",
    allStates: "అన్ని రాష్ట్రాలు",
    allCommodities: "అన్ని వస్తువులు",
    allMarkets: "అన్ని మార్కెట్లు",
    state: "రాష్ట్రం",
    commodity: "వస్తువు",
    market: "మార్కెట్",
    resetFilters: "ఫిల్టర్‌లను రీసెట్ చేయండి",
    liveMandiPrices: "లైవ్ మండి ధరలు",
    realTimeIntelligence: "స్మార్ట్ నిర్ణయాల కోసం నిజ-సమయ మార్కెట్ ఇంటెలిజెన్స్",
    price: "ధర",
    msp: "MSP",
    status: "స్థితి",
    suggestion: "సూచన",
    lastUpdated: "నవీకరించబడింది",
    marketBased: "మార్కెట్ ఆధారిత",
    profit: "లాభం",
    loss: "నష్టం",
    sellNow: "అమ్మండి",
    wait: "వేచి ఉండండి",
    tryGovtProcurement: "ప్రభుత్వ కొనుగోలు",
    fetchingData: "డేటాను పొందుతోంది...",
    noPricesAvailable: "ధరలు అందుబాటులో లేవు.",
    best: "ఉత్తమం",
    today: "ఈరోజు",
    marketInsights: "మార్కెట్ అంతర్దృష్టులు",
    deepAnalysis: "ప్రస్తుత మార్కెట్ ట్రెండ్స్ లోతైన విశ్లేషణ",
    yesterdayPrice: "నిన్నటి ధర",
    yesterday: "నిన్న",
    weeklyComparison: "వారపు పోలిక",
    historicalTrend: "చారిత్రక ట్రెండ్ (3 నెలలు)",
    avgPrice: "సగటు ధర",
    highest: "అత్యధికం",
    lowest: "అత్యల్పం",
  },
  hi: {
    dashboard: "डैशबोर्ड",
    insights: "अंतर्दृष्टि",
    addPrice: "कीमत जोड़ें",
    profile: "प्रोफ़ाइल",
    smartMandiSystem: "स्मार्ट मंडी इंटेलिजेंस सिस्टम",
    realTimeInsights: "सर्वोत्तम मूल्य पर बेचने में आपकी मदद करने के लिए रीयल-टाइम बाज़ार अंतर्दृष्टि",
    topCommodity: "आज की शीर्ष वस्तु",
    highestMarketPrice: "उच्चतम बाज़ार मूल्य",
    marketTrend: "बाज़ार का रुझान",
    marketsUp: "बाज़ार ऊपर",
    bullish: "तेजी",
    stable: "स्थिर",
    strong: "मजबूत",
    neutral: "तटस्थ",
    loading: "लोड हो रहा है...",
    allStates: "सभी राज्य",
    allCommodities: "सभी वस्तुएं",
    allMarkets: "सभी बाजार",
    state: "राज्य",
    commodity: "वस्तु",
    market: "बाज़ार",
    resetFilters: "फ़िल्टर रीसेट करें",
    liveMandiPrices: "लाइव मंडी की कीमतें",
    realTimeIntelligence: "स्मार्ट निर्णयों के लिए रीयल-टाइम बाज़ार बुद्धिमत्ता",
    price: "कीमत",
    msp: "MSP",
    status: "स्थिति",
    suggestion: "सुझाव",
    lastUpdated: "अंतिम अद्यतन",
    marketBased: "बाज़ार आधारित",
    profit: "लाभ",
    loss: "नुकसान",
    sellNow: "अभी बेचें",
    wait: "रुको",
    tryGovtProcurement: "सरकारी खरीद",
    fetchingData: "डेटा प्राप्त किया जा रहा है...",
    noPricesAvailable: "कोई मूल्य उपलब्ध नहीं है।",
    best: "सर्वश्रेष्ठ",
    today: "आज",
    marketInsights: "बाज़ार अंतर्दृष्टि",
    deepAnalysis: "वर्तमान बाजार के रुझानों का गहन विश्लेषण",
    yesterdayPrice: "कल की कीमत",
    yesterday: "कल",
    weeklyComparison: "साप्ताहिक तुलना",
    historicalTrend: "ऐतिहासिक रुझान (3 महीने)",
    avgPrice: "औसत कीमत",
    highest: "उच्चतम",
    lowest: "न्यूनतम",
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');

  const t = (key) => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
